name: Add approved label

on:
  push:
    branches:
      - main
      - release/*

jobs:
  labelWhenApproved:
  steps:
    - name: Label apppoved pull requests
      uses: abinoda/label-when-approved-action@1.0.5
      env:
        APPROVALS: "1"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ADD_LABEL: "approved"
